### ISSUE TITLE
BUG: active_site.dat.gz not downloadable anymore

### ISSUE THREAD

**Issue by JWDebler** [ccdmb/predector#40]
**Describe the bug**
The URL for `active_site.dat.gz` may have changed, as it is not listed on [ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/](ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/) anymore.

**Comment by darcyabjones** [comment]
Looks like the latest Pfam doesn't have the active sites anymore.
I have a feeling that Pfam-A.regions.tsv might contain that info, but it's in a different format so pfamscan wont use it.

Looks like we'll have to do without active sites.

**Comment by JWDebler** [comment]
can we use an 'old' one instead? It seems to have disappeared as of Pfam 34, but is still in 33.1 (ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam33.1/)

**Comment by darcyabjones** [comment]
We could, but we don't actually use the active sites for anything.
Is there a reason that you would especially want to keep it?
I'd rather have the latest HMMs than the active sites.

The only place that the active sites appear is in the output is in the GFF file for the proteins. Which I like, but i don't think many people will use.

FYI. Currently running on a test dataset before I push a new version up.

Looks like just setting the h5py version <3 fixes the deepsig issue. We'll either update or ditch it after the paper is published. It's a shame it isn't better.
I've just ditched the active site info for now but it's easy enough to reintroduce later on.

**Comment by JWDebler** [comment]
In that case might as well remove it completely.

**Comment by darcyabjones** [comment]
It's gone in the new version of Predector.
Thanks.

**Comment by darcyabjones** [comment]
Closing for now, please reopen if it's still an issue but I haven't had any myself.

**Comment by paulamool** [comment]
Something may have changed at EBI 
Received a connetion error for ftp://ftp.ebi.ac.uk/  

"--2021-10-15 00:47:57--  ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.dat.gz
    (try:20) => ‘Pfam-A.hmm.dat.gz’
  Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.197.74|:21... failed: Connection timed out.
  Giving up."

I changed url in nextflow.config from ftp to http and it seems okay for a few runs (4) but getting the same error again.

pfam_hmm_url = "http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz"
pfam_dat_url = "http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.dat.gz"

**Comment by paulamool** [comment]
No problem, I thought that after posting
