### ISSUE TITLE
effectorp3.0 support

### ISSUE THREAD

**Issue by xizhesun** [ccdmb/predector#42]
Dear  developer,

I noticed that the effectorP has updated to 3.0 [https://github.com/JanaSperschneider/EffectorP-3.0](url)

So whether the predector support the effector3.0 or not?

Thanks,
Xizhe

**Comment by darcyabjones** [comment]
Hi Xizhe,

Unfortunately EffectorP 3 isn't supported yet.
I plan to update the pipeline a bit in the coming months, but for now we're still trying to get version 1 published.

I'll try to get EffectorP3 to run as part of the pipeline next week, so you'll get the results of it in the output.
But it probably won't get integrated into the ranking function until we start properly on version 2 later this year.

I'll reply to this post when it's ready to go.

Cheers,
Darcy

**Comment by darcyabjones** [comment]
Related to #38

**Comment by xizhesun** [comment]
Thank you, Darcy. You work so hard! Have a nice weekend!

Cheers,
Xizhe

**Comment by darcyabjones** [comment]
This is now implemented in 1.1.0-alpha.

I'm hoping we'll be able to include all of the classifier scores individually (EP3 seems to only report probabilities > 0.5).
For now it just reports the scores that EP3 does and fills the others with the NA value '.'.

Hope you're well. Thanks again for getting in touch.
