### ISSUE TITLE
FEATURE REQUEST:  secretomeP

### ISSUE THREAD

**Issue by xizhesun** [ccdmb/predector#45]
**What kind of feature are you proposing?**
secretomeP analysis, which related to the Non-classical secreted proteins. It could be a reference for the effector candidates.

**Comment by darcyabjones** [comment]
Hi Xizhe,

Previously we've found that secretomeP isn't precise enough to be useful for this task.
It's fallen out of favour with most of the bioinformatician that I know.

E.g.
https://www.frontiersin.org/articles/10.3389/fpls.2015.01168/full
https://www.frontiersin.org/articles/10.3389/fpls.2016.01451/full

The other aspect is the installation.
I remember having to install it years ago, and there is a dependency that can only be obtained by emailing the author directly.
It took a week for them to email me the installer.

Doesn't seem worth the trouble.

**Comment by xizhesun** [comment]
yeah, I agree with you! It's really hard for the installation. I also install one year ago. I successfully run it on a ubuntu machine. but failed on the WSL of my laptop.

**Comment by darcyabjones** [comment]
Thanks
