### ISSUE TITLE
FEATURE REQUEST: Add a check to `install.sh` and conda register scripts to check for correct SignalP6 model

### ISSUE THREAD

**Issue by darcyabjones** [ccdmb/predector#65]
#64 appears to be an issue with the "fast" model missing from the signalp6 distribution.

It seems like it would be easy to accidentally download the slow_sequential model rather than the fast one.
We need a check in the -register script for conda to check for the fast version.

At that point we can either 1) download the fast model (which appears to be possible without registering from the documentation), or we can raise a nicer error that is clear about what happened.

The SignalP6 models are really big, so avoiding doubling container sizes would be ideal, but It might be less of a barrier if we just deal with it internally.

**Comment by JWDebler** [comment]
There also seems to have been an update to the filename, in that the latest is called "signalp-6.0b.fast.tar.gz"

**Comment by darcyabjones** [comment]
Thanks, yeah released like 3 days ago.

That seems to be the actual issue in #64, the new version doesn't copy the model files automatically during install for some reason.
Just my luck hey!? Been working on some nice updates for weeks, make a semi big deal of it on twitter/conference and I miss a version update.

I really wish there was a good alternative to SignalP.
Their whole license deal is such a pain in the arse. 

I still think it's worth having a check in there. Genuinely seems to be something that would be easy to do

**Comment by darcyabjones** [comment]
Commit https://github.com/ccdmb/predector/commit/e38e80251213f29191287410217d691c59db06e6 adds a new SignalP 6 recipe.
It handles the issue we had, ie. that the models were in a separate folder to the actual python package (requiring that you put it there yourself, rather than letting the installer do it).

It also raises a friendlier error if the wrong distribution was provided and explicitly checks for the presence of "fast" models.

Should be good to go in next release.
