### ISSUE TITLE
BUG: result files point to dead links when cleanup = true (or after running nextflow clean -f)

### ISSUE THREAD

**Issue by IdoBar** [ccdmb/predector#84]
**Describe the bug**
When running the pipeline, the result files are pointing to links inside `work` dir, however, if using the `cleanup = true` option (or after running `nextflow clean -f`), all intermediate files are removed from that folder, so the links are "dead".

**To Reproduce**
Add `cleanup = true` to `nextflow.config` file (doesn't need to be in a specific scope, see the [documentation](https://www.nextflow.io/docs/latest/config.html#miscellaneous)).
Run the pipeline with `nextflow run -profile test,conda -resume -r 1.2.6 ccdmb/predector -c nextflow.config`

Alternatively, run the pipeline as usual with `nextflow run -profile test,conda -resume -r 1.2.6 ccdmb/predector` and then run `nextflow clean -f` and check the content of the `results` folder

**Expected behavior**
The results should be saved in the 'results` folder even after cleanup. 

**Screenshots or copy-pasted terminal output**
![image](https://user-images.githubusercontent.com/16175388/168614842-cabf5703-601f-494d-a13e-a97e5373be91.png)

**Operating system (please enter the following information as appropriate):**
 - OS/Linux distribution: Red Hat Enterprise Linux Server release 7.6 (Maipo)
 - Dependency management: Conda

**Additional context**
I think it would be better to copy the files over to the `results` folder, to make sure the results are saved after cleanup of the working directory.
I think that it can be done by adding `mode: 'copy'` to the `publishDir` directive in line 390 of [main.nf](https://github.com/ccdmb/predector/blob/master/main.nf).

**Comment by darcyabjones** [comment]
Hi @IdoBar 

Thanks for the suggestion and PR.
We've discussed this internally before.
I guess it does make sense to have copy publishing as the default.

My main reason for keeping them sym-linked was to avoid large copies and taking up too much disk space.
I wrote this with the intention that it could handle many genomes at once, but a lot of people seem to just run it on their laptops for one or two.

I previously documented the copy symlink thing here: https://github.com/ccdmb/predector/wiki#accessing-and-copying-the-results .

As a compromise, what do you think about making copy the default, but provide a profile to allow using the symlink publish mode as well?

**Comment by IdoBar** [comment]
Thanks @darcyabjones 

I completely missed this in the documentation :see_no_evil:
Your solution will work quite well!

Cheers, Ido

**Comment by IdoBar** [comment]
I'm happy to give it a try, but it'll have to wait a bit until I find the time and get my head around how CLI options are implemented in the workflow (shouldn't be complicated, I'll just have to dig through the code a bit).

**Comment by IdoBar** [comment]
Well, it didn't take me too long :smirk: (see https://github.com/IdoBar/predector/commit/8937104296387f1cad3d5de0367dddccec6bebf5)
I tested it and it works as expected, have a look if you're happy with my documentation at the Usage info (probably worth also updating the relevant documentation on the Wiki page).
